{{- $metrics := tpl "{{ tpl .Values.operator.name . }}-metrics" . -}}
{{- $controlPlane := "controller-manager" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $metrics }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $metrics }}
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "{{ .Values.releaseVersion }}"
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: {{ $controlPlane }}
