{{- $metricsReader := tpl "{{ tpl .Values.operator.name . }}-metrics-reader" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ $metricsReader }}
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: {{ tpl .Values.operator.name . }}
    app.kubernetes.io/part-of: {{ tpl .Values.operator.name . }}
  name: {{ $metricsReader }}
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
