{{- $proxy := tpl "{{ tpl .Values.operator.name . }}-proxy" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $proxy }}
  labels:
    app.kubernetes.io/name: {{ $proxy }}
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "{{ .Values.releaseVersion }}"
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
