# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
{{- $metricsReader := tpl "{{ tpl .Values.operator.name . }}-metrics-reader" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $metricsReader }}
  labels:
    app.kubernetes.io/name: {{ $metricsReader }}
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "{{ .Values.releaseVersion }}"
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
