---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: {{ .Values.kubearchive.namespace }}-metrics-reader
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: {{ .Values.kubearchive.namespace }}-operator
    app.kubernetes.io/part-of: {{ .Values.kubearchive.namespace }}-operator
  name: {{ .Values.kubearchive.namespace }}-metrics-reader
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
