---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: {{ .Values.kubearchive.namespace }}-proxy-rolebinding
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: {{ .Values.kubearchive.namespace }}-operator
    app.kubernetes.io/part-of: {{ .Values.kubearchive.namespace }}-operator
  name: {{ .Values.kubearchive.namespace }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.kubearchive.namespace }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.kubearchive.namespace }}-operator
    namespace: {{ .Values.kubearchive.namespace }}
