---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: {{ .Values.kubearchive.namespace }}-service
    app.kubernetes.io/instance: {{ .Values.kubearchive.namespace }}-operator-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: {{ .Values.kubearchive.namespace }}-operator
    app.kubernetes.io/part-of: {{ .Values.kubearchive.namespace }}-operator
  name: {{ .Values.kubearchive.namespace }}-operator-metrics-service
  namespace: {{ .Values.kubearchive.namespace }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: controller-manager
