{{- $proxy := tpl "{{ tpl .Values.operator.name . }}-proxy" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ $proxy }}
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: {{ tpl .Values.operator.name . }}
    app.kubernetes.io/part-of: {{ tpl .Values.operator.name . }}
  name: {{ $proxy }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $proxy }}
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.operator.name . }}
    namespace: {{ .Release.Namespace }}
