# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ tpl .Values.operator.cert . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ tpl .Values.operator.cert . }}"
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "{{ .Values.releaseVersion }}"
spec:
  dnsNames:
    - "{{ tpl .Values.operator.name . }}-webhooks.{{ .Release.Namespace }}.svc"
    - "{{ tpl .Values.operator.name . }}-webhooks.{{ .Release.Namespace }}.svc.cluster.local"
  issuerRef:
    kind: Issuer
    name: {{ .Release.Name }}
  secretName: {{ tpl .Values.operator.secret . }}
