# permissions for end users to edit kubearchiveconfigs.
{{- $configEditor := tpl "{{ tpl .Values.operator.name . }}-config-editor" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ $configEditor }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: {{ tpl .Values.operator.name . }}
    app.kubernetes.io/part-of: {{ tpl .Values.operator.name . }}
  name: {{ $configEditor }}
rules:
  - apiGroups:
      - kubearchive.kubearchive.org
    resources:
      - kubearchiveconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kubearchive.kubearchive.org
    resources:
      - kubearchiveconfigs/status
    verbs:
      - get
