# permissions for end users to view kubearchiveconfigs.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: {{ .Values.kubearchive.namespace }}config-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: {{ .Values.kubearchive.namespace }}-operator
    app.kubernetes.io/part-of: {{ .Values.kubearchive.namespace }}-operator
  name: {{ .Values.kubearchive.namespace }}config-viewer-role
rules:
  - apiGroups:
      - kubearchive.kubearchive.org
    resources:
      - kubearchiveconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubearchive.kubearchive.org
    resources:
      - kubearchiveconfigs/status
    verbs:
      - get
