# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
# permissions for end users to edit kubearchiveconfigs.
{{- $configEditor := tpl "{{ tpl .Values.operator.name . }}-config-editor" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $configEditor }}
  labels:
    app.kubernetes.io/name: {{ $configEditor }}
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "{{ .Values.releaseVersion }}"
rules:
  - apiGroups:
      - kubearchive.kubearchive.org
    resources:
      - kubearchiveconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kubearchive.kubearchive.org
    resources:
      - kubearchiveconfigs/status
    verbs:
      - get
