# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
# permissions for end users to view kubearchiveconfigs.
{{- $configViewer := tpl "{{ tpl .Values.operator.name . }}-config-viewer" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $configViewer }}
  labels:
    app.kubernetes.io/name: {{ $configViewer }}
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "{{ .Values.releaseVersion }}"
rules:
  - apiGroups:
      - kubearchive.kubearchive.org
    resources:
      - kubearchiveconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubearchive.kubearchive.org
    resources:
      - kubearchiveconfigs/status
    verbs:
      - get
