apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: {{ .Values.kubearchive.namespace }}-operator-leader-election
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: {{ .Values.kubearchive.namespace }}-operator
    app.kubernetes.io/part-of: {{ .Values.kubearchive.namespace }}-operator
    app.kubernetes.io/managed-by: kustomize
  name: {{ .Values.kubearchive.namespace }}-operator-leader-election
  namespace: {{ .Values.kubearchive.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.kubearchive.namespace }}-operator-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ .Values.kubearchive.namespace }}-operator
    namespace: {{ .Values.kubearchive.namespace }}
