# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
{{- $leaderElection := tpl "{{ tpl .Values.operator.name . }}-leader-election" . -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $leaderElection }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $leaderElection }}
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "{{ .Values.releaseVersion }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $leaderElection }}
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.operator.name . }}
    namespace: {{ .Release.Namespace }}
