# Prometheus Monitor Service (Metrics)
{{- $metrics := tpl "{{ tpl .Values.operator.name . }}-metrics" . -}}
{{- $controlPlane := "controller-manager" -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: {{ $controlPlane }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ $metrics }}
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: {{ tpl .Values.operator.name . }}
    app.kubernetes.io/part-of: {{ tpl .Values.operator.name . }}
    app.kubernetes.io/managed-by: kustomize
  name: {{ $metrics }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: {{ $controlPlane }}
