# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
# Prometheus Monitor Service (Metrics)
{{- $metrics := tpl "{{ tpl .Values.operator.name . }}-metrics" . -}}
{{- $controlPlane := "controller-manager" -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $metrics }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $metrics }}
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "{{ .Values.releaseVersion }}"
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: {{ $controlPlane }}
