# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ tpl .Values.operator.name . }}
  labels:
    app.kubernetes.io/name: {{ tpl .Values.operator.name . }}
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "{{ .Values.releaseVersion }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ tpl .Values.operator.name . }}
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.operator.name . }}
    namespace: {{ .Release.Namespace }}
