---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ tpl .Values.operator.name . }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: {{ tpl .Values.operator.name . }}
    app.kubernetes.io/part-of: {{ tpl .Values.operator.name . }}
  name: {{ tpl .Values.operator.name . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ tpl .Values.operator.name . }}
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.operator.name . }}
    namespace: {{ .Release.Namespace }}
