# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: splunk-flow
spec:
  filters:
    - tag_normaliser: {}
  match:
    - exclude:
        namespaces:
          - cert-manager
          - kube-node-lease
          - kube-public
          - kube-system
          - kubearchive
          - splunk-operator
    - select: {}
  globalOutputRefs:
    - splunk-output
