# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubearchive-logging-writer
data:
  POD_ID: "cel:metadata.uid"
  QUERY: "search * | spath \"kubernetes.pod_id\" | search \"kubernetes.pod_id\"=\"{POD_ID}\" | spath \"kubernetes.container_name\" | search \"kubernetes.container_name\"=\"{CONTAINER_NAME}\" | sort time | table \"message\""
  LOG_URL: "https://splunk-single-standalone-service.splunk-operator.svc.cluster.local:8089"
