# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Secret
metadata:
  name: kubearchive-logging
stringData:
  HEADERS: |
    https://splunk-single-standalone-service.splunk-operator.svc.cluster.local:8089:
      Authorization: "Basic YWRtaW46cGFzc3dvcmQ="
