# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: enterprise.splunk.com/v4
kind: Standalone
metadata:
  name: single
  finalizers:
    - enterprise.splunk.com/delete-pvc
