# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kubearchive-database-credentials
  namespace: kubearchive
  labels:
    app.kubernetes.io/name: kubearchive-database-credentials
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "${NEXT_VERSION}"
stringData:
  DATABASE_KIND: ""
  DATABASE_PORT: ""
  DATABASE_URL: ""
  DATABASE_DB: ""
  DATABASE_USER: ""
  DATABASE_PASSWORD: ""
