# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: tekton-results-import
  namespace: kubearchive
data:
  # Base64 encoded values for Tekton Results database
  DATABASE_URL: "database-url"
  DATABASE_PORT: "NTQzMg==" # 5432
  DATABASE_USER: "database-user"
  DATABASE_PASSWORD: "database-password"
  DATABASE_DB: "dGVrdG9uX3Jlc3VsdHM=" # tekton_results
