# yamllint disable rule:braces
{{- $caName := tpl "{{ .Release.Name }}-ca" . -}}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "{{ $caName }}"
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $caName }}"
spec:
  isCA: true
  commonName: kubearchive-ca-certificate
  secretName: "{{ $caName }}"
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: "{{ $caName }}"
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "{{ .Release.Name }}"
spec:
  ca:
    secretName: "{{ $caName }}"
