{{- if .Values.integrations.observability.enabled }}
{{ $appName := "traces-collector" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $appName }}"
  labels:
    app: "{{ $appName }}"
spec:
  selector:
    matchLabels:
      app: "{{ $appName }}"
  template:
    metadata:
      labels:
        app: "{{ $appName }}"
    spec:
      containers:
      - env:
        - name: SPAN_STORAGE_TYPE
          value: memory
        - name: JAEGER_DISABLED
          value: "false"
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        image: "jaegertracing/all-in-one:{{ .Values.integrations.observability.imageTag }}"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 14269
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        name: "{{ $appName }}"
        ports:
        - containerPort: 16686
          name: query
          protocol: TCP
        - containerPort: 4318
          name: http-otlp
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 14269
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ $appName }}"
  name: "{{ $appName }}"
spec:
  type: ClusterIP
  selector:
    app: "{{ $appName }}"
  ports:
  - name: http-otlp
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: http-query
    port: 16686
    protocol: TCP
    targetPort: 16686
{{- end }}
