{{- if .Values.integrations.observability.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-lgtm
  template:
    metadata:
      labels:
        app: grafana-lgtm
    spec:
      containers:
        - name: grafana-lgtm
          image: grafana/otel-lgtm:latest
          ports:
            - containerPort: 3000
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 9411
          volumeMounts:
            - name: otelcol-config
              mountPath: /otel-lgtm/otelcol-config.yaml
              subPath: otelcol-config.yaml
      volumes:
        - name: otelcol-config
          configMap:
            name: otelcol-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-lgtm
spec:
  selector:
    app: grafana-lgtm
  ports:
    - name: grafana
      port: 3000
    - name: otel-grpc
      port: 4317
    - name: otel-http
      port: 4318
    - name: zipkin
      port: 9411
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-config
data:
  otelcol-config.yaml: |
    {{- .Files.Get "conf/grafana-otelcol-config.yaml" | required "Empty 'conf/grafana-otelcol-config.yaml" | nindent 4 }}

{{- end }}
