# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
run:
  timeout: 10m
  build-tags:
    - integration
linters:
  enable:
    - bodyclose
    - containedctx
    - fatcontext
    - goimports
    - gosec
    - nilerr
    - nilnil
    - usestdlibvars
    - wastedassign
    - unparam
linters-settings:
  govet:
    enable-all: false
    disable-all: false
    enable:
      - loopclosure
      - nilness
      - shadow
