# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
run:
  timeout: 10m
linters:
  enable:
    - bodyclose
    - containedctx
    - fatcontext
    - gofmt
    - gosec
    - nilerr
    - usestdlibvars
    - wastedassign
