# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
defaultLdflags:
  - -X main.version={{ .Git.Tag }}
  - -X main.commit={{ .Git.FullCommit }}
  - -X main.date={{ .Date }}
defaultBaseImage: registry.access.redhat.com/ubi10/ubi-minimal
