= Installation

ifeval::["{page-component-display-version}" == "main"]
:download-path: https://github.com/kubearchive/kubearchive/releases/latest/download
endif::[]
ifeval::["{page-component-display-version}" != "main"]
:download-path: https://github.com/kubearchive/kubearchive/releases/download/{page-component-display-version}
endif::[]

This document explains how to install and configure KubeArchive in your Kubernetes cluster.

== Prerequisites

* A PostgreSQL instance (+v16.6) protected with TLS (can be self-signed, KubeArchive does not verify it)
// renovate: datasource=github-releases depName=cert-manager packageName=cert-manager/cert-manager
* CertManager is installed on the Kubernetes cluster (+v1.17.2)

== Prepare the Database

. Create a user and a password for KubeArchive to use.
. Create a database for KubeArchive, with admin permissions granted to the new user.
  Configure its timezone as UTC and its locale as UTF-8.
. Clone the
link:https://github.com/kubearchive/kubearchive[KubeArchive repository]
and run the SQL migrations for your database, in this example PostgreSQL:
+
[source,bash,subs="attributes"]
----
git clone https://github.com/kubearchive/kubearchive.git --branch={page-component-display-version}
cd kubearchive
migrate \
    -verbose -path integrations/database/postgresql/migrations/ \
    -database postgresql://<kubearchive-user>:<kubearchive-password>@<postgresql-host>:<postgresql-port>/<kubearchive-database> \
    up
----
+
This configures the DB with the proper schema so KubeArchive can write and read resources.

More information about the schema and its customization in the
xref:integrations/database.adoc#_configuration_and_customization[Database Integration]
section.

[TIP]
====
A Kubernetes Job named `kubearchive-schema-migration` is installed in the `kubearchive` namespace.
Use this as an example to build your migration automations.
====

[_install_and_configure_kubearchive]
== Install and Configure KubeArchive

. Apply the release YAML to install KubeArchive:
+
[source,bash,subs="attributes"]
----
kubectl apply -n kubearchive -f {download-path}/kubearchive.yaml
----

. Provide the credentials for the database in the `kubearchive-database-credentials` secret:
+
[source, bash]
----
kubectl patch secret -n kubearchive kubearchive-database-credentials \
--patch='{"stringData": {
"DATABASE_URL": "database.example.com", <1>
"DATABASE_PASSWORD": "password" <2>
}}'
----
<1> The database URL
<2> The database password

+
More info about this Secret in the
xref:integrations/database.adoc#_configuration_and_customization[Database Integration]
section.

. Restart the `kubearchive-api-server` and `kubearchive-sink` Deployments to update
the database credentials secret:
+
[source,bash]
----
kubectl rollout -n kubearchive restart deployment kubearchive-sink kubearchive-api-server
----

== Next steps

Continue with
xref:getting-started/kubearchive-api.adoc[]
to learn how to access archived resources.
