= Installation

ifeval::["{page-component-display-version}" == "main"]
:download-path: https://github.com/kubearchive/kubearchive/releases/latest/download
endif::[]
ifeval::["{page-component-display-version}" != "main"]
:download-path: https://github.com/kubearchive/kubearchive/releases/download/{page-component-display-version}
endif::[]

This document explains how to install and configure KubeArchive in your Kubernetes cluster.

== Prerequisites

* A PostgreSQL instance (+v16.6) protected with TLS (can be self-signed, KubeArchive does not verify it)
* CertManager is installed on the Kubernetes cluster (+v1.9.1)
* Knative Eventing is installed on the Kubernetes cluster (+v1.17.4)

== Prepare the Database

. Create a database user `kubearchive`.
. With a DB admin account, apply the schema provided in the [filename]`kubearchive.sql` file
within the KubeArchive release:
+
[source,bash,subs="attributes"]
----
wget {download-path}/kubearchive.sql
psql -h database.example.com \
-U admin \
-f kubearchive.sql
----

More information about the schema and its customization in the
xref:integrations/database.adoc#_configuration_and_customization[Database Integration]
section.

== Configure Knative Eventing

KubeArchive uses a broker to avoid missing Kubernetes resource updates. By default, it is an `MTChannelBasedBroker`, but
the broker type can be changed if desired.

[IMPORTANT]
====
Knative Eventing strongly recommends using one of the
link:https://knative.dev/docs/eventing/brokers/broker-types/[other broker types]
in production environments.
====

[_install_and_configure_kubearchive]
== Install and Configure KubeArchive

. Apply the release YAML to install KubeArchive:
+
[source,bash,subs="attributes"]
----
kubectl apply -n kubearchive -f {download-path}/kubearchive.yaml
----

. Provide the credentials for the database in the `kubearchive-database-credentials` secret:
+
[source, bash]
----
kubectl patch secret -n kubearchive kubearchive-database-credentials \
--patch='{"stringData": {
"DATABASE_URL": "database.example.com", <1>
"DATABASE_PASSWORD": "password" <2>
}}'
----
<1> The database URL
<2> The database password

+
More info about this Secret in the
xref:integrations/database.adoc#_configuration_and_customization[Database Integration]
section.

. Restart the `kubearchive-api-server` and `kubearchive-sink` Deployments to update
the database credentials secret:
+
[source,bash]
----
kubectl rollout -n kubearchive restart deployment kubearchive-sink kubearchive-api-server
----

== Next steps

Continue with
xref:getting-started/kubearchive-api.adoc[]
to learn how to access archived resources.
