= Installation

ifeval::["{page-component-display-version}" == "main"]
:download-path: https://github.com/kubearchive/kubearchive/releases/latest/download
endif::[]
ifeval::["{page-component-display-version}" != "main"]
:download-path: https://github.com/kubearchive/kubearchive/releases/download/{page-component-display-version}
endif::[]

This document explains how to install and configure KubeArchive in your Kubernetes cluster.

== Prerequisites

* A PostgreSQL instance
* CertManager is installed on the Kubernetes cluster (+v1.9.1)
* Knative Eventing is installed on the Kubernetes cluster (+v1.15.0)

== Prepare the Database

. Create ada user and a password for KubeArchive to use.
. Create a database for KubeArchive, with admin permissions granted to the user you just created.
. As the user, execute the `kubearchive.sql` we provide for initializing the database, located at:
+
[source,bash,subs="attributes"]
----
wget {download-path}/kubearchive.sql
psql -h database.example.com -U username ... -f kubearchive.sql
----
+
This file creates a PostgreSQL schema, a table for KubeArchive and other stuff KubeArchive
requires.

== Configure Knative Eventing

By default, Knative Eventing use `MTChannelBasedBroker` as the class for any Broker that does not explicitly define its
class and uses `InMemoryChannel` as the backing channel implementation. Knative Eventing strongly recommends using a
native broker implementation for production workloads instead. We recommend the Apache Kafka Broker.

. If you need a Kafka cluster, follow the
link:https://strimzi.io/docs/operators/latest/deploying#con-strimzi-installation-methods_str[Strimzi deployment instructions]
. Follow the
link:https://knative.dev/docs/eventing/brokers/broker-types/kafka-broker/#installation[Knative Eventing Kafka Broker installation instructions]
. Create a ConfigMap named kafka-broker-config in the knative-eventing namespace. Use
link:https://knative.dev/docs/eventing/brokers/broker-types/kafka-broker/#configure-a-kafka-broker[this ConfigMap]
as a guide.
. Update the config-br-defaults ConfigMap in the knative-eventing namespace
+
[source,bash]
----
kubectl apply -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-br-defaults
  namespace: knative-eventing
data:
  default-br-config: |
    clusterDefault:
      brokerClass: MTChannelBasedBroker
      apiVersion: v1
      kind: ConfigMap
      name: config-br-default-channel
      namespace: knative-eventing
    namespaceDefaults:
      kubearchive:
        brokerClass: Kafka
        apiVersion: v1
        kind: ConfigMap
        name: kafka-broker-config
        namespace: knative-eventing
EOF
----

Knative Eventing supports other Broker types as well. You can learn more about them
link:https://knative.dev/docs/eventing/brokers/broker-types/[here]

== Install and Configure KubeArchive

. Apply the release YAML to install KubeArchive:
+
[source,bash,subs="attributes"]
----
kubectl apply -n kubearchive -f {download-path}/kubearchive.yaml
----

. Provide the credentials for the database in the `kubearchive-database-credentials` secret:
+
[source,bash]
----
cat <<EOF > /tmp/patch.yaml
stringData:
  DATABASE_KIND: postgresql
  DATABASE_PORT: <postgresql-port>
  DATABASE_URL: <postgresql-url>
  DATABASE_USER: <kubearchive-username>
  DATABASE_DB: <kubearchive-database>
  DATABASE_PASSWORD: <kubearchive-password>
EOF
kubectl patch -n kubearchive secret kubearchive-database-credentials --patch-file /tmp/patch.yaml
----

. Restart the `kubearchive-api-server` and `kubearchive-sink` Deployments to update
the database credentials secret:
+
[source,bash]
----
kubectl rollout -n kubearchive restart deployment kubearchive-sink kubearchive-api-server
----

== Next steps

Continue with
xref:getting-started/kubearchive-api.adoc[]
to learn how to access archived resources.
