# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: kronicler
spec:
  mariaDbRef:
    name: kronicler
  characterSet: utf8
  collate: utf8_general_ci
  # Delete the resource in the database whenever the CR gets deleted.
  # Alternatively, you can specify Skip in order to omit deletion.
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
