# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: kronicler
spec:
  mariaDbRef:
    name: kubarchive
  privileges:
    - "ALL PRIVILEGES"
  database: kronicler
  table: "*"
  username: kronicler
  grantOption: true
  host: "%"
  # Delete the resource in the database whenever the CR gets deleted.
  # Alternatively, you can specify Skip in order to omit deletion.
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
