# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: kubearchive
spec:
  rootPasswordSecretKeyRef:
    name: kubearchive
    key: root-password

  username: kubearchive
  passwordSecretKeyRef:
    name: kubearchive
    key: password
  database: kubearchive

  port: 3306

  storage:
    size: 1Gi

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi

  metrics:
    enabled: false
