# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Secret
metadata:
  name: kubearchive
  labels:
    k8s.mariadb.com/watch: ""
stringData:
  password: Databas3Passw0rd
  root-password: root
