# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: kronicler
spec:
  mariaDbRef:
    name: kronicler
  passwordSecretKeyRef:
    name: kronicler
    key: password
  # This field is immutable and defaults to 10
  maxUserConnections: 20
  host: "%"
  # Delete the resource in the database whenever the CR gets deleted.
  # Alternatively, you can specify Skip in order to omit deletion.
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
