# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: kubearchive-broker
  namespace: kubearchive
  labels:
    app.kubernetes.io/name: kubearchive-broker
    app.kubernetes.io/component: sink
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "${NEXT_VERSION}"
spec:
  delivery:
    retry: 4
    backoffPolicy: exponential
    # ISO 8601 format
    backoffDelay: PT0.5S
    deadLetterSink:
      ref:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        name: kubearchive-dls
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: kubearchive-dls
  namespace: kubearchive
  labels:
    app.kubernetes.io/name: kubearchive-dls
    app.kubernetes.io/component: sink
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "${NEXT_VERSION}"
spec:
  delivery:
    retry: 4
    backoffPolicy: exponential
    # ISO 8601 format
    backoffDelay: PT0.5S
