# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: kronicler-broker
  namespace: kronicler
  labels:
    app.kubernetes.io/name: kronicler-broker
    app.kubernetes.io/component: sink
    app.kubernetes.io/part-of: kronicler
    app.kubernetes.io/version: "${NEXT_VERSION}"
spec:
  delivery:
    retry: 4
    backoffPolicy: linear
    # ISO 8601 format
    backoffDelay: PT0.5S
    deadLetterSink:
      ref:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        name: kronicler-dls
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: kronicler-dls
  namespace: kronicler
  labels:
    app.kubernetes.io/name: kronicler-dls
    app.kubernetes.io/component: sink
    app.kubernetes.io/part-of: kronicler
    app.kubernetes.io/version: "${NEXT_VERSION}"
spec:
  delivery:
    retry: 4
    backoffPolicy: linear
    # ISO 8601 format
    backoffDelay: PT0.5S
