//go:build !ignore_autogenerated

// Copyright KubeArchive Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeArchiveConfig) DeepCopyInto(out *KubeArchiveConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeArchiveConfig.
func (in *KubeArchiveConfig) DeepCopy() *KubeArchiveConfig {
	if in == nil {
		return nil
	}
	out := new(KubeArchiveConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeArchiveConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeArchiveConfigList) DeepCopyInto(out *KubeArchiveConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubeArchiveConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeArchiveConfigList.
func (in *KubeArchiveConfigList) DeepCopy() *KubeArchiveConfigList {
	if in == nil {
		return nil
	}
	out := new(KubeArchiveConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeArchiveConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeArchiveConfigSpec) DeepCopyInto(out *KubeArchiveConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeArchiveConfigSpec.
func (in *KubeArchiveConfigSpec) DeepCopy() *KubeArchiveConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KubeArchiveConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeArchiveConfigStatus) DeepCopyInto(out *KubeArchiveConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeArchiveConfigStatus.
func (in *KubeArchiveConfigStatus) DeepCopy() *KubeArchiveConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KubeArchiveConfigStatus)
	in.DeepCopyInto(out)
	return out
}
