# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubearchive
resources:
  - monitoring-otel-collector.yaml
  - monitoring-servicemonitor.yaml

configMapGenerator:
  - name: otel-collector-conf
    namespace: kubearchive
    files:
      - otel-collector-config.yaml
