---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources.yaml

configMapGenerator:
  - name: otel-collector-conf
    namespace: observability
    files:
      - otel-collector-config.yaml
  - name: otelcol-config
    namespace: observability
    files:
      - otel-collector-grafana.yaml
