# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'kubearchive-otel-collector'
          static_configs:
            - targets: ['localhost:8888']

processors:
  batch:

exporters:
  debug:
  otlphttp:
    endpoint: "http://grafana-lgtm.observability.svc.cluster.local:4318"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [debug, otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp]
