# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-lgtm
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-lgtm
  template:
    metadata:
      labels:
        app: grafana-lgtm
    spec:
      containers:
        - name: grafana-lgtm
          image: grafana/otel-lgtm:latest
          ports:
            - containerPort: 3000
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 9411
            - containerPort: 9090
          volumeMounts:
            - name: otelcol-config
              mountPath: /otel-lgtm/otelcol-config.yaml
              subPath: otel-collector-grafana.yaml
      volumes:
        - name: otelcol-config
          configMap:
            name: otelcol-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-lgtm
  namespace: observability
spec:
  selector:
    app: grafana-lgtm
  ports:
    - name: grafana
      port: 3000
    - name: otel-grpc
      port: 4317
    - name: otel-http
      port: 4318
    - name: zipkin
      port: 9411
    - name: prometheus
      port: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app: otel-collector
spec:
  ports:
    - name: otlp-http
      port: 4318
    - name: metrics
      port: 8888
  selector:
    app: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app: otel-collector
spec:
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector:latest
          command:
            - "/otelcol"
            - "--config=/conf/otel-collector-config.yaml"
          ports:
            - containerPort: 4318
            - containerPort: 8888
          volumeMounts:
            - name: otel-collector-conf
              mountPath: /conf
      volumes:
        - configMap:
            name: otel-collector-conf
          name: otel-collector-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-tracing
  namespace: knative-eventing
data:
  backend: "zipkin"
  zipkin-endpoint: "http://grafana-lgtm.kronicler.svc.cluster.local:9411"
  sample-rate: "1"
