# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Secret
metadata:
  name: kubearchive-logging
  namespace: kubearchive
  labels:
    app.kubernetes.io/name: kubearchive-logging
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "${NEXT_VERSION}"
type: Opaque
data:
  Authorization: QmFzaWMgWVdSdGFXNDZjR0Z6YzNkdmNtUT0= # notsecret
