---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ tpl .Values.sink.watchRole . }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
