---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ tpl .Values.sink.watchRole . }}
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.sink.name . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ tpl .Values.sink.watchRole . }}
