---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ tpl .Values.sink.watchRole . }}"
  labels:
    app.kubernetes.io/name: "{{ tpl .Values.sink.watchRole . }}"
    app.kubernetes.io/component: sink
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "{{ .Values.releaseVersion }}"
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.sink.name . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ tpl .Values.sink.watchRole . }}
