---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ tpl .Values.sink.name . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ tpl .Values.sink.name . }}"
    app.kubernetes.io/component: sink
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "{{ .Values.releaseVersion }}"

