---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.sink.name . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.sink.replicas }}
  selector:
    matchLabels: &labels
      app: {{ tpl .Values.sink.name . }}
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: {{ tpl .Values.sink.name . }}
      containers:
        - name: {{ tpl .Values.sink.name . }}
          image: {{ .Values.sink.image }}
          envFrom:
            # Provide DB URL, user, password, database and port as env vars
            - secretRef:
                name: {{ .Values.database.secret }}
          env:
            - name: KUBEARCHIVE_OTEL_MODE
              value: "disabled"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: ""
---
kind: Service
apiVersion: v1
metadata:
  name: {{ tpl .Values.sink.name . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ tpl .Values.sink.name . }}
  ports:
    - protocol: {{ .Values.sink.protocol }}
      port: {{ .Values.sink.port }}
      targetPort: {{ .Values.sink.targetPort }}
