---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.sink.name . }}
spec:
  replicas: {{ .Values.sink.replicas }}
  selector:
    matchLabels: &labels
      app: {{ tpl .Values.sink.name . }}
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: {{ tpl .Values.sink.name . }}
      volumes:
        - name: sink-filters
          configMap:
            name: sink-filters
      containers:
        - name: {{ tpl .Values.sink.name . }}
          image: {{ .Values.sink.image }}
          volumeMounts:
            - mountPath: "{{ .Values.sink.mountPath }}"
              name: "sink-filters"
              readOnly: true
          envFrom:
            # Provide DB URL, user, password, database and port as env vars
            - secretRef:
                name: {{ .Values.database.secret }}
          env:
            - name: MOUNT_PATH
              value: "{{ .Values.sink.mountPath }}"
            {{- include "kubearchive.v1.otel.env" . | nindent 12 }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ tpl .Values.sink.name . }}
spec:
  selector:
    app: {{ tpl .Values.sink.name . }}
  ports:
    - protocol: {{ .Values.sink.protocol }}
      port: {{ .Values.sink.port }}
      targetPort: {{ .Values.sink.targetPort }}
