---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.sink.name . }}
spec:
  replicas: {{ .Values.sink.replicas }}
  selector:
    matchLabels: &labels
      app: {{ tpl .Values.sink.name . }}
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: {{ tpl .Values.sink.name . }}
          image: {{ .Values.sink.image }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.database.secret . }}
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.database.secret . }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.database.secret . }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_URL
              value: {{ tpl .Values.database.url . }}
            - name: POSTGRES_PORT
              value: "{{ .Values.database.service.port }}"
{{ include "kubearchive.v1.otel.env" .Values.sink | indent 12 }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ tpl .Values.sink.name . }}
  namespace: {{ .Values.kubearchive.namespace }}
spec:
  selector:
    app: {{ tpl .Values.sink.name . }}
  ports:
    - protocol: {{ .Values.sink.protocol }}
      port: {{ .Values.sink.port }}
      targetPort: {{ .Values.sink.targetPort }}
