---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: {{ tpl .Values.sink.name . }}
  namespace: {{ .Release.Namespace }}
spec:
  broker: {{ .Release.Name }}-broker
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: {{ tpl .Values.sink.name . }}
