# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kronicler-api-server"
  namespace: kronicler
  labels:
    app.kubernetes.io/name: "kronicler-api-server"
    app.kubernetes.io/component: api-server
    app.kubernetes.io/part-of: kronicler
    app.kubernetes.io/version: "${NEXT_VERSION}"
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: kronicler-api-server
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: kronicler-api-server
      volumes:
        - name: tls-secret
          secret:
            secretName: kronicler-api-server-tls
        - name: logging-secret
          secret:
            secretName: kronicler-logging
      containers:
        - name: kronicler-api-server
          image: ko://github.com/kronicler/kronicler/cmd/api
          resources:
            requests:
              cpu: 200m
              # 90% of the limit
              # See recommendations at https://tip.golang.org/doc/gc-guide#Memory_limit
              memory: 230Mi
            limits:
              # Currently the API is sitting at 630m on performance tests
              cpu: 700m
              memory: 256Mi
          volumeMounts:
            - name: tls-secret
              readOnly: true
              mountPath: /etc/kronicler/ssl/
            - mountPath: /data/logging
              name: logging-secret
          envFrom:
            # Provide DB URL, user, password, database and port as env vars
            - secretRef:
                name: kronicler-database-credentials
          env:
            - name: KRONICLER_ENABLE_PPROF
              value: "true"
            - name: LOG_LEVEL
              value: INFO
            - name: GIN_MODE
              value: "release"
            - name: KRONICLER_OTEL_MODE
              value: "disabled"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: ""
            - name: KRONICLER_OTLP_SEND_LOGS
              value: "false"
            - name: OTEL_GO_X_DEPRECATED_RUNTIME_METRICS
              value: "false"
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: CACHE_EXPIRATION_AUTHORIZED
              value: "10m"
            - name: CACHE_EXPIRATION_UNAUTHORIZED
              value: "1m"
            - name: KRONICLER_LOGGING_DIR
              value: /data/logging
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: 8081
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
              scheme: HTTPS
---
kind: Service
apiVersion: v1
metadata:
  name: "kronicler-api-server"
  namespace: kronicler
  labels:
    app.kubernetes.io/name: "kronicler-api-server"
    app.kubernetes.io/component: api-server
    app.kubernetes.io/part-of: kronicler
    app.kubernetes.io/version: "${NEXT_VERSION}"
spec:
  selector:
    app: kronicler-api-server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: server
