# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "kronicler-api-server-certificate"
  namespace: kronicler
  labels:
    app.kubernetes.io/name: "kronicler-api-server-certificate"
    app.kubernetes.io/component: api-server
    app.kubernetes.io/part-of: kronicler
    app.kubernetes.io/version: "${NEXT_VERSION}"
spec:
  isCA: false
  commonName: kronicler-api-server
  secretName: "kronicler-api-server-tls"
  duration: 720h  # 30 days
  renewBefore: 360h  # 15 days
  subject:
    organizations:
      - kronicler
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - digital signature
    - key encipherment
  dnsNames:
    - localhost
    - kronicler-api-server
    - "kronicler-api-server.kronicler.svc"
  issuerRef:
    name: "kronicler"
    kind: Issuer
    group: cert-manager.io
