# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "kubearchive-api-server"
  labels:
    app.kubernetes.io/name: "kubearchive-api-server"
    app.kubernetes.io/component: api-server
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "${NEXT_VERSION}"
subjects:
  - kind: ServiceAccount
    name: kubearchive-api-server
    namespace: kubearchive
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubearchive-api-server
