{{- if .Values.database.enabled -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ tpl .Values.database.name . }}
  name: {{ tpl .Values.database.name . }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.database.volumes.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ tpl .Values.database.name . }}
  name: {{ tpl .Values.database.name . }}
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      app: {{ tpl .Values.database.name . }}
  template:
    metadata:
      labels:
        app: {{ tpl .Values.database.name . }}
    spec:
      containers:
        - name: {{ tpl .Values.database.name . }}
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.database.service.port }}
          envFrom:
            - secretRef:
                name: {{ tpl .Values.database.secret . }}
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: {{ .Values.database.volumes.name }}
      volumes:
        - name: {{ .Values.database.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ tpl .Values.database.name . }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
    app: {{ tpl .Values.database.name . }}
  name: {{ tpl .Values.database.name . }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.database.volumes.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ tpl .Values.database.name .  }}
  name: {{ tpl .Values.database.name . }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
  selector:
    app: {{ tpl .Values.database.name . }}
{{- end }}
