{{- if .Values.database.enabled -}}
{{- $dbNs := "databases" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $dbNs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.database.name . }}-ddl
  namespace: {{ $dbNs }}
  labels:
    app: {{ tpl .Values.database.name . }}
data:
  ddl.sql: |
  {{- tpl (.Files.Get "conf/ddl-resource.sql") . | required "Empty 'conf/ddl-resource.sql" | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ tpl .Values.database.name . }}
  name: {{ tpl .Values.database.name . }}
  namespace: {{ $dbNs }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.database.volumes.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ tpl .Values.database.name . }}
  name: {{ tpl .Values.database.name . }}
  namespace: {{ $dbNs }}
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      app: {{ tpl .Values.database.name . }}
  template:
    metadata:
      labels:
        app: {{ tpl .Values.database.name . }}
    spec:
      containers:
        - name: {{ tpl .Values.database.name . }}
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.database.service.port }}
          env:
            - name: POSTGRES_DB
              value: root
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: password  # notsecret
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: {{ .Values.database.volumes.name }}
            {{- if not .Values.global.production }}
            - name: ddl
              mountPath: "/docker-entrypoint-initdb.d"
            {{- end }}
      volumes:
        - name: {{ .Values.database.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ tpl .Values.database.name . }}
        {{- if not .Values.global.production }}
        - name: ddl
          configMap:
            name: {{ tpl .Values.database.name . }}-ddl
        {{- end }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
    app: {{ tpl .Values.database.name . }}
  name: {{ tpl .Values.database.name . }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.database.volumes.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ tpl .Values.database.name .  }}
  name: {{ tpl .Values.database.name . }}
  namespace: {{ $dbNs }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
  selector:
    app: {{ tpl .Values.database.name . }}
{{- end }}
