# yamllint disable rule:braces
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ tpl .Values.database.name . }}
  name: {{ tpl .Values.database.name . }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.database.volumes.storage }}
