# yamllint disable rule:braces
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ tpl .Values.database.name . }}
  name: {{ tpl .Values.database.name . }}
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      app: {{ tpl .Values.database.name . }}
  template:
    metadata:
      labels:
        app: {{ tpl .Values.database.name . }}
    spec:
      containers:
        - name: {{ tpl .Values.database.name . }}
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.database.service.port }}
          envFrom:
            - secretRef:
                name: {{ tpl .Values.database.secret . }}
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: {{ .Values.database.volumes.name }}
      volumes:
        - name: {{ .Values.database.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ tpl .Values.database.name . }}
