# yamllint disable rule:braces
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
    app: {{ tpl .Values.database.name . }}
  name: {{ tpl .Values.database.name . }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.database.volumes.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
