# yamllint disable rule:braces
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app: {{ tpl .Values.database.name . }}
  name: {{ tpl .Values.database.secret . }}
data:
  POSTGRES_DB: {{ default "postgresdb" .Values.database.postgresData.dbName | b64enc | quote }}
  POSTGRES_USER: {{ default "ps_user" .Values.database.postgresData.dbUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ default "P0stgr3sdbP@ssword" .Values.database.postgresData.dbPassword | b64enc | quote }} # notsecret
