# yamllint disable rule:braces
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ tpl .Values.database.name .  }}
  name: {{ tpl .Values.database.name . }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
  selector:
    app: {{ tpl .Values.database.name . }}
