= Configuring Global Filters on Kronicler

Kronicler allows cluster owners to configure global filters. These are applied
to any Kronicler namespace containing a `KroniclerConfig` custom resource.

To configure the global filters create a `KroniclerConfig` in the
"kronicler" namespace. When it is created in the "kronicler" namespace
these filters are considered global:

[source,yaml]
----
---
apiVersion: kronicler.kronicler.org/v1alpha1
kind: KroniclerConfig
metadata:
  name: kronicler
  namespace: kronicler
spec:
  resources:
    - selector:
        apiVersion: v1
        kind: Pod
      archiveOnDelete: "true"
----

== Interaction With Local Filters

Global filters only work in namespaces containing a `KroniclerConfig` custom
resource. These can be understood as "local" filters in opposition with global
filters. Both global and local filters are combined with an "OR" type of logic
and used for that specific namespace.

For example the following `KroniclerConfig` in the namespace "my-team" Kronicler
archives jobs as long as they have `status.startTime` and deletes them when they
have `status.completionTime`. However Kronicler also archives pods when they are
about to be deleted, as configured in the global filters in the previous section:

[source,yaml]
----
---
apiVersion: kronicler.kronicler.org/v1alpha1
kind: KroniclerConfig
metadata:
  name: kronicler
  namespace: my-team
spec:
  resources:
    - selector:
        apiVersion: batch/v1
        kind: Job
      archiveWhen: has(status.startTime)
      deleteWhen: has(status.completionTime)
----

For example the following `KroniclerConfig` in the namespace "production" Kronicler
only archives pods when they are about to be deleted, as configured in the global filters
in the previous section:

[source,yaml]
----
---
apiVersion: kronicler.kronicler.org/v1alpha1
kind: KroniclerConfig
metadata:
  name: kronicler
  namespace: production
spec: {}
----

[NOTE]
====
The 'KroniclerConfig` resource must be named "kronicler".
====
