= KubeArchive Logs

This page refers to the logs produced by KubeArchive. To see how KubeArchive
integrates with logging systems, check
xref:integrations/logging.adoc[].

== Environment variables

KubeArchive supports environment variables to configure logging:

* `LOG_LEVEL`: specifies the minimum log level to be logged. Defaults to `"INFO"`.
Supported values are "DEBUG", "INFO", "WARN" and "ERROR".
* `KLOG_LEVEL`: specifies the log level for the tooling used by Kubernetes libraries.
Defaults to "0". Supported values range from "0" to any arbitrary integer. We normally
find "7" to be a balanced level when it comes to verbosity and usefulness.

To change these variables you can use `kubectl set env`:

[source,bash]
----
kubectl set -n kubearchive env deployment kubearchive-api-server LOG_LEVEL=DEBUG
kubectl set -n kubearchive env deployment kubearchive-operator KLOG_LEVEL=7
kubectl set -n kubearchive env deployment kubearchive-sink LOG_LEVEL=ERROR
----

[WARNING]
====
Pods automatically restart when their environment variables are changed.
====

== TraceID and SpanID

The KubeArchive Sink and API print logs with `trace-id` and `span-id`. If 
xref:configuration/observability.adoc[observability]
is configured, their values are correlated with the emitted traces.
If
xref:configuration/observability.adoc[observability]
is not configured, their values are generated and only used within
KubeArchive to correlate logs.

[NOTE]
====
The KubeArchive Operator logs do not have `trace-id` and `span-id`.
====
