= Upgrading KubeArchive

This document details the process to upgrade your KubeArchive installation.

[IMPORTANT]
====
* KubeArchive is not backward compatible with database changes.
  Both application and schema must be upgraded at the same time.
* Backup your database before doing a KubeArchive upgrade.
====

. Scale down KubeArchive:
+
[source,bash]
----
kubectl scale -n kubearchive deployment \
    kubearchive-sink \
    kubearchive-api-server \
    kubearchive-operator \
    --replicas 0
----

. Download the KubeArchive repository and switch to the version you would like to upgrade
to.
+
[source,bash]
----
git clone https://github.com/kubearchive/kubearchive.git --branch=v1.1.0 kubearchive-v1.1.0
----

. Run the database migrations:
+
[source,bash]
----
cd kubearchive-v1.1.0
migrate -verbose \
    -path integrations/database/postgresql/migrations/ \
    -database postgresql://<kubearchive-user>:<kubearchive-password>@<postgresql-host>:<postgresql-port>/<kubearchive-database> \
    up
----

. Apply the new KubeArchive manifests and scale up KubeArchive:
+
[source,bash]
----
kubectl apply -n kubearchive \
    -f https://github.com/kubearchive/kubearchive/releases/download/v1.1.0/kubearchive.yaml
kubectl scale -n kubearchive deployment \
    kubearchive-sink \
    kubearchive-api-server \
    kubearchive-operator \
    --replicas 1
----

. Check pods/deployments are running correctly:
+
[source,bash]
----
kubectl get -n kubearchive all
kubectl logs -n kubearchive deployment/kubearchive-sink
kubectl logs -n kubearchive deployment/kubearchive-api-server
kubectl logs -n kubearchive deployment/kubearchive-operator
----

== Handling Upgrade Or Downgrade Failure

When a migration fails the database version is modified to the failed migration but
left into a "dirty" state. That stops `migrate` from applying more migrations:

[source,text]
----
error: Dirty database version <VERSION>. Fix and force version.
----

When this happens inspect the state of the database to decide how to proceed.
After you fixed the problem, you need to force the database version with
link:https://github.com/golang-migrate/migrate/blob/master/GETTING_STARTED.md#forcing-your-database-version[the following command]
(continuing the PostgreSQL example):

[source,bash]
----
migrate -verbose \
    -path integrations/database/postgresql/migrations/ \
    -database postgresql://<kubearchive-user>:<kubearchive-password>@<postgresql-host>:<postgresql-port>/<kubearchive-database> \
    force <VERSION>
----

[WARNING]
====
If you fixed the database removing what the failed migration did and then fixed
the migration file you need to force `<VERSION - 1>`. If you fixed by completing
the failed migration then force `<VERSION>`. After `force` run `up` again
to make sure that all the migrations are applied.
====
