# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
# WARNING: this is intended to be applied in a single node
#   Kubernetes environment and just for testing purposes
---
apiVersion: v1
kind: Namespace
metadata:
  name: databases
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgresql
  name: postgresql
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
    app: postgresql
  name: postgresql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql
  name: postgresql
  namespace: databases
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: root
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: password  # notsecret
          readinessProbe:
            exec:
              command:
                - psql
                - -l
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgresql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: postgresql
  namespace: databases
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgresql
