# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: kubearchive
spec:
  instances: 1
  postgresql:
    # https://www.postgresql.org/docs/current/auth-pg-hba-conf.html
    # columns: connection-type database user address auth-options
    pg_hba:
      - hostnossl  all  all  all  reject
  bootstrap:
    initdb:
      database: kubearchive
      secret:
        name: kubearchive-user
      owner: kubearchive
  enableSuperuserAccess: true
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  storage:
    size: 1Gi
