# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Secret
metadata:
  name: kubearchive-logging
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: Y2hhbmdlbWU=  # notsecret
  user: YWRtaW4=
