# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: es-flow
spec:
  filters:
    - tag_normaliser: {}
  match:
    - exclude:
        namespaces:
          - cert-manager
          - cnpg-system
          - elastic-system
          - knative-eventing
          - kube-node-lease
          - kube-public
          - kube-system
          - kubearchive
          - mariadb-operator
          - postgresql
    - select: {}
  globalOutputRefs:
    - es-output
