# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kronicler
spec:
  version: 8.15.0
  count: 1
  elasticsearchRef:
    name: kronicler
