# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: kronicler
spec:
  fluentd:
    disablePvc: true
  fluentbit: {}
  controlNamespace: elastic-system
