# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubearchive-logging-reader
data:
  LOG_PROVIDERS: |
    https://kubearchive-es-http.elastic-system.svc.cluster.local:9200:
      tail:
        reverse: true
        path: /fluentd/_search
        method: GET
        params:
          q: ${QUERY}
          _source_includes: message
          sort: "@timestamp:desc"
          size: ${TAIL_LINES}
        json-path: "$.hits.hits[*]._source.message"
      full:
        reverse: false
        path: /fluentd/_search
        method: GET
        params:
          q: ${QUERY}
          _source_includes: message
          sort: "@timestamp:asc"
          size: 10000
        json-path: "$.hits.hits[*]._source.message"
