= Secret Rotation

This document lists every secret Kronicler uses in its processes that requires
rotation.

[IMPORTANT]
====
Secrets should be rotated each twice a year (each 6 months):

* January
* July
====

== Kronicler Organization

link:https://github.com/organizations/kronicler/settings/secrets/actions[Organization Secrets]

OCI_PASSWORD::
password for the robot account named after the variable OCI_USERNAME. Go to the
link:https://quay.io/organization/kronicler?tab=robots[Kronicler's Quay Organization]
and regenerate the token for the appropiate robot.

KRONICLER_BOT_SECRET::
to be done.

KRONICLER_RENOVATE_PRIVATE_KEY::
private key for the bot named `kronicler-renovate`. Go to
link:https://github.com/organizations/kronicler/settings/apps/kronicler-renovate[the kronicler-renovate app page]
and generate a new client secret.

== Kronicler Repository

PUSH_TO_MAIN_DEPLOY_KEY::
SSH private key used to push to the default branch from the release workflow. See
link:https://github.com/kronicler/kronicler/settings/keys[Kronicler's Release Keys]
and
link:https://github.com/kronicler/kronicler/settings/rules[Kronicler's Rulesets]
for more information. Generate a new SSH key, add it to Deploy Keys, and then replace
the secret value.
