# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "kronicler-operator-certificate"
  namespace: kronicler
  labels:
    app.kubernetes.io/name: "kronicler-operator-certificate"
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kronicler
    app.kubernetes.io/version: "${NEXT_VERSION}"
spec:
  dnsNames:
    - "kronicler-operator-webhooks.kronicler.svc"
    - "kronicler-operator-webhooks.kronicler.svc.cluster.local"
  issuerRef:
    kind: Issuer
    name: kronicler
  secretName: kronicler-operator-tls
