# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kronicler-operator-leader-election
  namespace: kronicler
  labels:
    app.kubernetes.io/name: kronicler-operator-leader-election
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kronicler
    app.kubernetes.io/version: "${NEXT_VERSION}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kronicler-operator-leader-election
subjects:
  - kind: ServiceAccount
    name: kronicler-operator
    namespace: kronicler
