# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: "kronicler-operator-webhooks"
  namespace: kronicler
  labels:
    app.kubernetes.io/name: "kronicler-operator-webhooks"
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kronicler
    app.kubernetes.io/version: "${NEXT_VERSION}"
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
      name: webhook-server
    - port: 8082
      protocol: TCP
      targetPort: 8082
      name: pprof-server
  selector:
    control-plane: controller-manager
