# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "kronicler-sink-watch"
  namespace: kronicler
  labels:
    app.kubernetes.io/name: "kronicler-sink-watch"
    app.kubernetes.io/component: sink
    app.kubernetes.io/part-of: kronicler
    app.kubernetes.io/version: "${NEXT_VERSION}"
subjects:
  - kind: ServiceAccount
    name: kronicler-sink
    namespace: kronicler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kronicler-sink-watch
