# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "kubearchive-sink-watch"
  namespace: kubearchive
  labels:
    app.kubernetes.io/name: "kubearchive-sink-watch"
    app.kubernetes.io/component: sink
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "${NEXT_VERSION}"
subjects:
  - kind: ServiceAccount
    name: kubearchive-sink
    namespace: kubearchive
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubearchive-sink-watch
