# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "kronicler-sink"
  namespace: kronicler
  labels:
    app.kubernetes.io/name: "kronicler-sink"
    app.kubernetes.io/component: sink
    app.kubernetes.io/part-of: kronicler
    app.kubernetes.io/version: "${NEXT_VERSION}"
