# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "kubearchive-sink"
  namespace: kubearchive
  labels:
    app.kubernetes.io/name: "kubearchive-sink"
    app.kubernetes.io/component: sink
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "${NEXT_VERSION}"
