# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubearchive-logging
data:
  POD_ID: "cel:metadata.uid"
  START: "cel:status.?startTime == optional.none() ? int(now()-duration('1h'))*1000000000: status.startTime"
  END: "cel:status.?startTime == optional.none() ? int(now()+duration('1h'))*1000000000: int(timestamp(status.startTime)+duration('72h'))*1000000000" # temporary workaround until CONTAINER_NAME is allowed on CEL expressions as variable: 3 days since start timestamp
  # END: "cel:(status.?containerStatuses.?filter(c, c.name == '{CONTAINER_NAME}')?[0].?state.?terminated.?finishedAt != optional.none()) ? timestamp(status.containerStatuses.filter(c, c.name == '{CONTAINER_NAME}')[0].state.terminated.finishedAt) : int(now()+duration('5m'))*1000000000"
  LOG_URL: "http://loki-gateway.grafana-loki.svc.cluster.local:80/loki/api/v1/query_range?query=%7Bstream%3D%22{POD_ID}-{CONTAINER_NAME}%22%7D&start={START}&end={END}&direction=forward&limit=10000 "
  LOG_URL_JSONPATH: "$.data.result[*].values[*][1]"
