# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubearchive-logging-reader
data:
  LOG_PROVIDERS: |
    http://loki-gateway.grafana-loki.svc.cluster.local:80:
      tail:
        reverse: true
        path: /loki/api/v1/query_range
        method: GET
        params:
          query: ${QUERY}
          start: ${START}
          limit: ${TAIL_LINES}
          direction: backward
        json-path: "$.data.result[*].values[*][1]"
      full:
        reverse: false
        path: /loki/api/v1/query_range
        method: GET
        timeout: 1m
        params:
          query: ${QUERY}
          start: ${START}
          limit: 300
          direction: forward
        json-path: "$.data.result[*].values[*][1]"
        pagination:
          next-cursor: "$.data.result[*].values[*][0]"
          param: start
          cursor-increment: 1
