# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
loki:
  limits_config:
    max_query_length: 0
    retention_period: 744h  # 31 days retention
    ingestion_rate_mb: 10
    ingestion_burst_size_mb: 20
    max_streams_per_user: 0
    max_line_size: 256000
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    discover_service_name: []
  # Enable authentication for basic auth support
  auth_enabled: true
  basic_auth:
    enabled: true
    existingSecret: loki-basic-auth
  storage:
    type: s3
    bucketNames:
      chunks: loki
      ruler: loki
      admin: loki
    s3:
      endpoint: loki-minio:9000
      region: us-east-1
      accessKeyId: loki
      secretAccessKey: supersecret
      s3ForcePathStyle: true
      insecure: true

  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h

  commonConfig:
    replication_factor: 1

  compactor:
    retention_enabled: true
    delete_request_store: s3

deploymentMode: Distributed

singleBinary:
  replicas: 0

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

# Distributed components configuration
ingester:
  replicas: 1
  autoscaling:
    enabled: false
  zoneAwareReplication:
    enabled: false
  persistence:
    enabled: true
    size: 10Gi
  affinity: {}
  podAntiAffinity:
    soft: {}
    hard: {}

querier:
  replicas: 1
  autoscaling:
    enabled: false
  affinity: {}

queryFrontend:
  replicas: 1

queryScheduler:
  replicas: 1

distributor:
  replicas: 1
  autoscaling:
    enabled: false
  affinity: {}

compactor:
  replicas: 1

indexGateway:
  replicas: 1
  maxUnavailable: 0
  affinity: {}

ruler:
  replicas: 1

# Disable bloom components for now (they can be enabled later for optimization)
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
bloomPlanner:
  replicas: 0
bloomBuilder:
  replicas: 0

# Gateway configuration for load balancing
gateway:
  enabled: true
  replicas: 1
  image:
    registry: docker.io
    repository: nginxinc/nginx-unprivileged
    tag: 1.24-alpine
  service:
    type: ClusterIP
    port: 80

# Enable Minio deployment within Loki chart
minio:
  enabled: true
  rootUser: loki
  rootPassword: supersecret
  mode: standalone
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      memory: 512Mi
  postJob:
    enabled: false
