---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ tpl .Values.apiServer.cert . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ tpl .Values.apiServer.cert . }}"
    app.kubernetes.io/component: api-server
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "{{ .Values.releaseVersion }}"
spec:
  isCA: false
  commonName: {{ tpl .Values.apiServer.name . }}
  secretName: "{{ tpl .Values.apiServer.secret . }}"
  duration: 720h  # 30 days
  renewBefore: 360h  # 15 days
  subject:
    organizations:
      - {{ required "An organization in the API Server certificate must be specified" .Release.Name }}
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - digital signature
    - key encipherment
  dnsNames:
    - localhost
    - {{ tpl .Values.apiServer.name . }}
    - "{{ tpl .Values.apiServer.name . }}.{{ .Release.Namespace }}.svc"
  issuerRef:
    name: "{{ .Release.Name }}"
    kind: Issuer
    group: cert-manager.io
