---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ tpl .Values.apiServer.name . }}"
  labels:
    app.kubernetes.io/name: "{{ tpl .Values.apiServer.name . }}"
    app.kubernetes.io/component: api-server
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "{{ .Values.releaseVersion }}"
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.apiServer.name . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ tpl .Values.apiServer.name . }}
