---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiServer.name }}
  namespace: {{ .Values.kubearchive.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiServer.testSA }}
  namespace: {{ .Values.kubearchive.namespace }}
