# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
site:
  title: KubeArchive
  url: https://kubearchive.github.io/kubearchive
  start_page: ROOT::index.adoc

content:
  sources:
    - url: ../
      branches: [HEAD, v*]
      tags: [v*, '!v0.0.0']  # v0.0.0 does not have docs so it makes Antora fail
      start_path: docs
      edit_url: false

asciidoc:
  attributes:
    experimental: ''

ui:
  supplemental_files: ./ui
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

antora:
  extensions:
    - require: '@antora/lunr-extension'
    - require: ./extensions/lunr-patch.js

output:
  clean: true

runtime:
  fetch: true
