# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: kronicler
spec:
  secretName: root-secret
  tlsUseSelfSigned: true
