# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: kubearchive
spec:
  secretName: root-secret
  tlsUseSelfSigned: true
