# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Secret
metadata:
  name: root-secret
type: Opaque
data:
  rootHost: JQ==
  rootPassword: cm9vdA==
  rootUser: cm9vdA==
