# Copyright Kronicler Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Namespace
metadata:
  name: kronicler
  labels:
    app.kubernetes.io/name: kronicler
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: kronicler
    app.kubernetes.io/version: "${NEXT_VERSION}"
