# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
name: "Assign reviewers by label"
on:
  workflow_call:
  pull_request_target:
    types:
      - unlabeled
      - labeled

jobs:
  assign_and_unassign:
    permissions:
      pull-requests: write
    name: assign and unassign reviewers
    runs-on: ubuntu-latest
    if: github.actor != 'kubearchive-renovate[bot]'
    steps:
      - name: Assign reviewers by label
        id: assign-reviewers
        uses: totallymoney/assign-reviewers-by-labels-action@v1.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
