# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
name: "Copy labels from referenced issue"
on:
  pull_request:
    types:
      - opened
      - edited
jobs:
  setup:
    uses: ./.github/workflows/log_run_details.yml
  copy-labels:
    runs-on: ubuntu-latest
    name: Copy labels from linked issues
    steps:
      - name: copy-labels
        uses: michalvankodev/copy-issue-labels@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
