# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
name: Documentation Build
run-name: Documentation Build
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      # Checkout 'fetch-tags' does not work properly, see https://github.com/actions/checkout/issues/701
      - name: Fecth tags
        run: git fetch --tags origin
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: '21'
      - name: Install Antora
        working-directory: ./docs
        run: npm ci
      - name: Generate Site
        working-directory: ./docs
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          path: docs/build/site
          retention-days: 1
