# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
name: golangci-lint
run-name: Linting Tests (golangci-lint)
on:
  schedule:
    # 9:25 UTC every 1st of month
    - cron: '25 09 1 * *'
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
permissions:
  contents: read
  pull-requests: read
  checks: write
jobs:
  setup:
    uses: ./.github/workflows/log_run_details.yml
  golangci:
    # See https://github.com/golangci/golangci-lint-action
    name: "golangci-lint security testing"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Display Go version
        run: go version
      - name: Generate operator code
        run: cmd/operator/generate.sh
      - name: Lint testing Go code
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          # When is scheduled, show all issues
          only-new-issues: ${{ github.event_name != 'schedule' }}
