# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
name: Static Code Analysis
run-name: Static Code Analysis
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
jobs:
  go-mod-tidy:
    name: go mod tidy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version: '1.25.5'
      - name: Run 'go mod tidy'
        run: |
          go mod tidy
      - name: Fail if there are any changes
        run: |
          git diff --exit-code go.sum
          git diff --exit-code go.mod
  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Run yamllint
        uses: karancode/yamllint-github-action@4052d365f09b8d34eb552c363d1141fd60e2aeb2
        with:
          yamllint_strict: false
          yamllint_comment: false
  license-checker:
    name: License Checker
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: '21'
      - name: Install License Checker
        run: npm install --global @kt3k/license-checker
      - name: Run License Checker
        run: license_checker
